part1: part1.cpp fractals.*
	g++ part1.cpp fractals.cpp -o part1
part2: part2.cpp fractals.*
	g++ part2.cpp fractals.cpp -o part2
part3: part3.cpp fractals.*
	g++ part3.cpp fractals.cpp -o part3
part4: part4.cpp fractals.*
	g++ part4.cpp fractals.cpp -o part4
part5: part5.cpp fractals.*
	g++ part5.cpp fractals.cpp -o part5
part6: part6.cpp fractals.*
	g++ part6.cpp fractals.cpp -o part6


############### DON'T TOUCH BELOW ##################
run%: part%
	@./part$* || :

